name: Terraform destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID : ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY : ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION : us-east-1
    steps:
      - name: Git checkout repo
        uses: actions/checkout@v3

      - name: SetUp terraform onto ubuntu for running commands
        uses: hashicorp/setup-terraform@v2

      - name: terraform initialization
        run: terraform init

      - name: terraform destroy
        run: terraform destroy --auto-approve
